### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cyouh95** [Jasmina88/codecademy_Jasmina_Debernardi#5]
(Exceeds Expectations)

Well done on this project! Good job on the analysis as well as data visualizations. In addition, your presentation slides were very thorough and clear in presenting your findings. Great attention to detail as well, such as using different text color to highlight your points!

As a further challenge, continue exploring these datasets and see if you could ask some more research questions about it. Try designing your own tests and continue to play around with different ways of data visualizations. Have fun!

**Comment by Jasmina88** [comment]
Thanks so much for the fast review, I hope this means I successfully completed the course.  I will explore the datasets some more and see what I can find!

Overall it's been a really fun journey, the lessons were nice and clear!

**Comment by cyouh95** [comment]
@Jasmina88 No problem! Congratulations on successfully completing the course, and glad to hear you've enjoyed it! :)
